pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/amorostodizara/jenkinsfile.git'
            }
        }

        stage('Compile') {
            steps {
                echo 'Compilation du code Java...'
                bat 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                echo 'Exécution du programme...'
                bat 'java HelloWorld'
            }
        }
    }

    post {
        success {
            echo 'Build réussi !'
        }
        failure {
            echo 'Build échoué !'
        }
    }
}
